# Generated by Django 4.2.10 on 2024-02-08 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_alter_articles_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='photo',
        ),
    ]
